test connection between multiple peers
The test added can fail (and others too probably), because sometimes
`this.#browser.on('serviceUp')` will return a `service.addresses` with
a IPv6 which yields the following error:
```bash
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect EINVAL fe80::fa9a:552c:fcb8:f2fb:41373 - Local (:::0)
    at internalConnect (node:net:1041:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at node:net:1134:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'connect',
  address: 'fe80::fa9a:552c:fcb8:f2fb',
  port: 41373
}
```